# Generated by Django 5.2.3 on 2025-06-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='language',
            field=models.CharField(blank=True, default='uz', max_length=2, null=True),
        ),
    ]
